version: '3.3'

services:
  bot:
    image: andaluh/telegram:v1
    container_name: andaluh_telegram
    restart: always
    build: .
    env_file:
      - .env
    volumes:
      - ./user_data:/var/www/data/andaluhbot_data